/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.primeiraopcao;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author Aluno
 */
public class PrimeriaOpção extends javax.swing.JFrame {

    /**
     * Creates new form PrimeriaOpção
     */
    public PrimeriaOpção() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgbCPU = new javax.swing.JProgressBar();
        pgbDISCO = new javax.swing.JProgressBar();
        pgbMEMORIA = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLeitura = new javax.swing.JButton();
        lblMINdisco = new javax.swing.JLabel();
        lblMEDdisco = new javax.swing.JLabel();
        lblMAXdisco = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblMINcpu = new javax.swing.JLabel();
        lblMEDcpu = new javax.swing.JLabel();
        lblMAXcpu = new javax.swing.JLabel();
        lblMINmemoria = new javax.swing.JLabel();
        lblMEDmemoria = new javax.swing.JLabel();
        lblMAXmemoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("CPU");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("DISCO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("MEMÓRIA");

        btnLeitura.setText("Fazer leitura dos dados");
        btnLeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeituraActionPerformed(evt);
            }
        });

        lblMINdisco.setText("0");

        lblMEDdisco.setText("0");

        lblMAXdisco.setText("0");

        jLabel7.setText("min");

        jLabel8.setText("med");

        jLabel9.setText("max");

        jLabel10.setText("min");

        jLabel11.setText("med");

        jLabel12.setText("max");

        jLabel13.setText("min");

        jLabel14.setText("max");

        jLabel15.setText("med");

        lblMINcpu.setText("0");

        lblMEDcpu.setText("0");

        lblMAXcpu.setText("0");

        lblMINmemoria.setText("0");

        lblMEDmemoria.setText("0");

        lblMAXmemoria.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMINcpu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMEDcpu)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMINmemoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMEDmemoria)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMINdisco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMEDdisco)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel9))
                            .addComponent(btnLeitura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMAXdisco)
                            .addComponent(lblMAXcpu)
                            .addComponent(lblMAXmemoria)))
                    .addComponent(pgbCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pgbDISCO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pgbMEMORIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pgbCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(lblMINcpu))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(lblMAXcpu))
                    .addComponent(jLabel15)
                    .addComponent(lblMEDcpu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbDISCO, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(lblMINdisco)
                        .addComponent(lblMAXdisco))
                    .addComponent(jLabel8)
                    .addComponent(lblMEDdisco))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(pgbMEMORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(lblMINmemoria)
                            .addComponent(lblMEDmemoria)
                            .addComponent(lblMAXmemoria))))
                .addGap(49, 49, 49)
                .addComponent(btnLeitura)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Integer mincpu = 100;
    Integer mediacpu = 0;
    Integer maxcpu = 0;
    Integer cpucontador = 0;
    Integer cputotal = 0;
    
    Integer mindisco = 100;
    Integer mediadisco = 0;
    Integer maxdisco = 0;
    Integer discocontador = 0;
    Integer discototal = 0;
    
    Integer minmemoria = 100;
    Integer mediamemoria = 0;
    Integer maxmemoria = 0;
    Integer memoriacontador = 0;
    Integer memoriatotal = 0;
    
    private void btnLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeituraActionPerformed
        
        Random cpu = new Random();
        Integer cpunumero = cpu.nextInt(101);
        cpucontador++ ; 
        cputotal = cputotal + cpunumero ;
        mediacpu = cputotal / cpucontador;
        lblMEDcpu.setText(String.format("%d",cpunumero));
        lblMINcpu.setText((mincpu)+ "%");
        lblMAXcpu.setText((maxcpu)+ "%");
        pgbCPU.setValue(cpunumero);
        pgbCPU.setStringPainted(true);
        lblMINcpu.setForeground(Color.red);
        lblMAXcpu.setForeground(Color.blue);
        
        if(cpunumero > maxcpu){
            maxcpu = cpunumero;
        }
        if(cpunumero < mincpu){
            mincpu = cpunumero;
        }
        
        lblMAXcpu.setText(String.format("%d%%",maxcpu));
        lblMINcpu.setText(String.format("%d%%",mincpu));
        lblMEDcpu.setText(String.format("%d%%",mediacpu));
        
        
        Random disco = new Random();
        Integer disconumero = disco.nextInt(101);
        discocontador++ ; 
        discototal = discototal + disconumero ;
        mediadisco = discototal / discocontador;
        lblMEDdisco.setText(String.format("%d",disconumero));
        lblMINdisco.setText((mindisco)+ "%");
        lblMAXdisco.setText((maxdisco)+ "%");
        pgbDISCO.setValue(disconumero);
        pgbDISCO.setStringPainted(true);
        lblMINdisco.setForeground(Color.red);
        lblMAXdisco.setForeground(Color.blue);
        
        if(disconumero > maxdisco){
            maxdisco = disconumero;
        }
        if(disconumero < mindisco){
            mindisco = disconumero;
        }
        
        lblMAXdisco.setText(String.format("%d",maxdisco) + "GB");
        lblMINdisco.setText(String.format("%d",mindisco) + "GB");
        lblMEDdisco.setText(String.format("%d",mediadisco) + "GB");
        
        
        Random memoria = new Random();
        Integer memorianumero = memoria.nextInt(101);
        memoriacontador++ ; 
        memoriatotal = memoriatotal + memorianumero ;
        mediamemoria = memoriatotal / memoriacontador;
        lblMEDmemoria.setText(String.format("%d",memorianumero));
        lblMINmemoria.setText((minmemoria)+ "%");
        lblMAXmemoria.setText((maxmemoria)+ "%");
        pgbMEMORIA.setValue(memorianumero);
        pgbMEMORIA.setStringPainted(true);
        lblMINmemoria.setForeground(Color.red);
        lblMAXmemoria.setForeground(Color.blue);
        
        if(memorianumero > maxmemoria){
            maxmemoria = memorianumero;
        }
        if(memorianumero < minmemoria){
            minmemoria = memorianumero;
        }
        
        lblMAXmemoria.setText(String.format("%d",maxmemoria) + "GB");
        lblMINmemoria.setText(String.format("%d",minmemoria) + "GB");
        lblMEDmemoria.setText(String.format("%d",mediamemoria) + "GB");
    }//GEN-LAST:event_btnLeituraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeriaOpção.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeriaOpção.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeriaOpção.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeriaOpção.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeriaOpção().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeitura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblMAXcpu;
    private javax.swing.JLabel lblMAXdisco;
    private javax.swing.JLabel lblMAXmemoria;
    private javax.swing.JLabel lblMEDcpu;
    private javax.swing.JLabel lblMEDdisco;
    private javax.swing.JLabel lblMEDmemoria;
    private javax.swing.JLabel lblMINcpu;
    private javax.swing.JLabel lblMINdisco;
    private javax.swing.JLabel lblMINmemoria;
    private javax.swing.JProgressBar pgbCPU;
    private javax.swing.JProgressBar pgbDISCO;
    private javax.swing.JProgressBar pgbMEMORIA;
    // End of variables declaration//GEN-END:variables
}
